# ==========================
# General
spring.application.name=foodstore

# ==========================
# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}


# ==========================
# Email service
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.socketFactory.port=${MAIL_SMTP_SOCKETFACTORY_PORT}
spring.mail.properties.mail.smtp.socketFactory.class=${MAIL_SMTP_SOCKETFACTORY_CLASS}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS_ENABLE}
spring.mail.properties.mail.smtp.starttls.required=${MAIL_SMTP_STARTTLS_REQUIRED}
spring.mail.protocol=${MAIL_PROTOCOL}


# ==========================
# Perfil por defecto
spring.profiles.active=dev