spring.application.name=foodstore

# DB (si la us?s)
spring.datasource.url=jdbc:mysql://localhost:3306/rotiseriaBD?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logs
logging.level.root=INFO
logging.level.org.springframework.security=TRACE